### ISSUE TITLE
netcoreapp2.0 SCD console app targeting osx-x64 doesn't work on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by philippgille** [dotnet/core#1007]
# Issue Title

netcoreapp2.0 SCD console app targeting osx-x64 doesn't work on Mac OS X 10.10.4

# General

I created a simple "Hello World!"-app with .NET Core 2.0 like this (in a PowerShell command line window):

```powershell
> dotnet --version
2.0.0
> mkdir hwapp; cd hwapp
... snip
> dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
... snip
> code .
# In Visual Studio Code, select hwapp.csproj and add the following line below the TargetFramework:
# <RuntimeIdentifiers>osx-x64</RuntimeIdentifiers>
# Then continue with:
> dotnet publish -r osx-x64
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
... snip
> Add-Type -Assembly "System.IO.Compression.FileSystem"
> [io.compression.zipfile]::CreateFromDirectory("X:\path\to\hwapp\bin\Debug\netcoreapp2.0\osx-x64\publish
", "X:\path\to\hwapp\app.zip")
# Transfer the file to the Mac, for example with (assuming curl.exe is in the PATH):
> curl.exe -kT .\app.zip https://transfer.sh/hwapp.zip
https://transfer.sh/123someId123/hwapp.zip
```

Download the file on the Mac (in my case a Mac Mini), extract the archive, right click on the file `hwapp` and select "Open with...", then choose "Terminal".

The following error message appears in the terminal window (some names and paths redacted):

```
Last login: <redacted>
<redacted>:~ <redacted>$ /path/to/hwapp/hwapp ; exit;
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /path/to/hwapp/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /path/to/hwapp/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
logout

[Process exited]
```

So the message says that the SCD was built for Mac OS X 10.12. But my understanding was that the advantage of the new portable RIDs introduced with .NET Core 2.0 was that the SCDs were actually portable across multiple versions of the target operating system. I understand that this doesn't work when using NuGet packages that don't support the target OS, but this "Hello World!"-app shouldn't be limited by that.

**Comment by Petermarcu** [comment]
.NET Core 2.0 supports OSX 10.12 and higher. The same binary will work on 10.12 and greater so you don't need to worry about 10.13. It doesn't change the minimum system requirements of the binaries and in the case of .NET Core 2.0, the product relies on things that just aren't there in 10.10. If you stay away from crypto you may be able to run it on 10.11 but its not a supported scenario.

**Comment by Petermarcu** [comment]
I'm going to close this because things appear to be failing in the expected way on an unsupported OSX version. Please reopen if I missed something.

**Comment by philippgille** [comment]
The [RID catalog](https://github.com/dotnet/docs/blob/c72b699eac962a330fcb4732cbea035a724d1bf1/docs/core/rid-catalog.md) contains:

> ## OS X RIDs
> 
> - `osx-x64` (.NET Core 2.0 or later versions)
> - `osx.10.10-x64`
> - `osx.10.11-x64`
> - `osx.10.12-x64` (.NET Core 1.1 or later versions)

It doesn't say anywhere that from that list, OSX 10.12 is currently the *only* supported OSX version for .NET Core 2.0. In contrary, another paragraph in the RID catalog says that the new portable RIDs make it easier to support multiple target operating systems, so of course you think that all OSX versions in that list are supported.

A link to [dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md(https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md) would be extremely helpful as well!

**Comment by Petermarcu** [comment]
I've made a PR here to clarify. https://github.com/dotnet/docs/pull/3324

**Comment by philippgille** [comment]
Thanks a lot!
