### ISSUE TITLE
Compilation error migrating when migrating to 2.1.0-rc1-final

### ISSUE THREAD

**Issue by sandipbhavsar** [dotnet/core#1543]
# Issue Title

Compilation error :: when migrating to 2.1.0-rc1-final

# General

Here is the compilation error ::

1) Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8032	An instance of analyzer Microsoft.AspNetCore.Mvc.Analyzers.AvoidHtmlPartialAnalyzer cannot be created from C:\Users\sbhavsar\.nuget\packages\microsoft.aspnetcore.mvc.analyzers\2.1.0-rc1-final\analyzers\dotnet\cs\Microsoft.AspNetCore.Mvc.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	

2) Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8032	An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from C:\Users\sbhavsar\.nuget\packages\microsoft.entityframeworkcore.analyzers\2.1.0-rc1-final\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by sadjadbp** [comment]
+1 when building project via VSTS, local is fine.

**Comment by sandipbhavsar** [comment]
I am getting build error on local

**Comment by natemcmaster** [comment]
Which version of the .NET Core CLI and/or Visual Studio are you using? You need at least the .NET Core CLI v2.1.300-rc1. cc @rynowak @pranavkm which version of VS has Roslyn 2.8.0?

**Comment by sadjadbp** [comment]
Locally I'm fine, for the VSTS build should I mention here or need to check with VSTS folks?

**Comment by natemcmaster** [comment]
I don't know how you're using VSTS, so it's hard to say. To debug this, run `dotnet --info` at the top of your build script to see which version is being used.

**Comment by pranavkm** [comment]
15.7 was the version that shipped with Roslyn 2.8.0.

**Comment by sadjadbp** [comment]
@natemcmaster I'm using a normal "Visual Studio build solution"

![image](https://user-images.githubusercontent.com/6307366/40152042-586af15c-5938-11e8-9f83-6a78e0bfbb09.png)

**Comment by sadjadbp** [comment]
Let me add a task to my build to install rc version of .net core  from https://github.com/dotnet/core/blob/master/release-notes/releases.csv and see if that'll fix it

**Comment by sadjadbp** [comment]
failed again, I've added a task for that "dotnet --info" and here is results

2018-05-17T02:03:45.5225042Z ##[section]Starting: dotnet info
2018-05-17T02:03:45.5231680Z ==============================================================================
2018-05-17T02:03:45.5231844Z Task         : .NET Core
2018-05-17T02:03:45.5232956Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2018-05-17T02:03:45.5233108Z Version      : 2.132.1
2018-05-17T02:03:45.5233421Z Author       : Microsoft Corporation
2018-05-17T02:03:45.5233529Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2018-05-17T02:03:45.5233642Z ==============================================================================
2018-05-17T02:03:47.3582933Z [command]C:\Windows\system32\chcp.com 65001
2018-05-17T02:03:47.3665347Z Active code page: 65001
2018-05-17T02:03:47.3705136Z [command]C:\hostedtoolcache\windows\dncs\2.1.300-rc1-008673\x64\dotnet.exe --info
2018-05-17T02:03:50.6403450Z .NET Core SDK (reflecting any global.json):
2018-05-17T02:03:50.6403717Z  Version:   2.1.300-rc1-008673
2018-05-17T02:03:50.6403849Z  Commit:    f5e3ddbe73
2018-05-17T02:03:50.6403926Z 
2018-05-17T02:03:50.6404061Z Runtime Environment:
2018-05-17T02:03:50.6404163Z  OS Name:     Windows
2018-05-17T02:03:50.6404281Z  OS Version:  10.0.14393
2018-05-17T02:03:50.6404380Z  OS Platform: Windows
2018-05-17T02:03:50.8154508Z  RID:         win10-x64
2018-05-17T02:03:50.8155372Z  Base Path:   C:\hostedtoolcache\windows\dncs\2.1.300-rc1-008673\x64\sdk\2.1.300-rc1-008673\
2018-05-17T02:03:50.8198264Z 
2018-05-17T02:03:50.8198622Z Host (useful for support):
2018-05-17T02:03:50.8198948Z   Version: 2.1.0-rc1
2018-05-17T02:03:50.8199373Z   Commit:  eb9bc92051
2018-05-17T02:03:50.8199541Z 
2018-05-17T02:03:50.8199710Z .NET Core SDKs installed:
2018-05-17T02:03:50.8199885Z   1.0.1 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8200062Z   1.0.4 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8200287Z   1.1.4 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8200462Z   1.1.5 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8200636Z   1.1.7 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8200829Z   1.1.8 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8201524Z   1.1.9 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8201931Z   2.0.0 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8202155Z   2.0.3 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8202333Z   2.1.2 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8202809Z   2.1.4 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8237118Z   2.1.100 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8237408Z   2.1.101 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8237575Z   2.1.102 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8237734Z   2.1.103 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8237916Z   2.1.104 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8238189Z   2.1.105 [C:\Program Files\dotnet\sdk]
2018-05-17T02:03:50.8243619Z   2.1.300-rc1-008673 [C:\hostedtoolcache\windows\dncs\2.1.300-rc1-008673\x64\sdk]
2018-05-17T02:03:50.8243831Z 
2018-05-17T02:03:50.8243986Z .NET Core runtimes installed:
2018-05-17T02:03:50.8244203Z   Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\hostedtoolcache\windows\dncs\2.1.300-rc1-008673\x64\shared\Microsoft.AspNetCore.All]
2018-05-17T02:03:50.8244908Z   Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\hostedtoolcache\windows\dncs\2.1.300-rc1-008673\x64\shared\Microsoft.AspNetCore.App]
2018-05-17T02:03:50.8245782Z   Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8246431Z   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8246997Z   Microsoft.NETCore.App 1.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8247448Z   Microsoft.NETCore.App 1.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8248126Z   Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8250192Z   Microsoft.NETCore.App 1.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8250854Z   Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8251322Z   Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8251938Z   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8252600Z   Microsoft.NETCore.App 1.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8253341Z   Microsoft.NETCore.App 1.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8253783Z   Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8254117Z   Microsoft.NETCore.App 1.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8254310Z   Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8254525Z   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8254700Z   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8254874Z   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8255073Z   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8255260Z   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8255450Z   Microsoft.NETCore.App 2.1.0-rc1 [C:\hostedtoolcache\windows\dncs\2.1.300-rc1-008673\x64\shared\Microsoft.NETCore.App]
2018-05-17T02:03:50.8255606Z 
2018-05-17T02:03:50.8255749Z To install additional .NET Core runtimes or SDKs:
2018-05-17T02:03:50.8255897Z   https://aka.ms/dotnet-download
2018-05-17T02:03:50.8349740Z ##[section]Finishing: dotnet info

**Comment by natemcmaster** [comment]
Afterthought: as long as your .sln file only has .NET Core or .NET Standard projects in it, another way to workaround this is to change your VSTS task to invoke `dotnet.exe build` on your .sln file instead of using the "Visual Studio Build" task.

**Comment by rjpackito** [comment]
I have the same problem as VS 15.7.1. I created a .NET Core 2.1 rc1 project. The same mistakes. What can be done?
