### ISSUE TITLE
.NET January 2026 non security Updates - .NET 10.0.2, .NET 9.0.12, .NET 8.0.23

### ISSUE THREAD

**Issue by rbhanda** [dotnet/core#10204]
# .NET January 2026 Update

## Release Notes
* [10.0.2](https://github.com/dotnet/core/blob/main/release-notes/10.0/10.0.2/10.0.2.md)
* [9.0.12](https://github.com/dotnet/core/blob/main/release-notes/9.0/9.0.12/9.0.12.md)
* [8.0.23](https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.23/8.0.23.md)

## Status

Asset Type | 10.0.1 | 9.0.12 | 8.0.23|  Notes | 
-- | :--: | :--:  | :--:  | :--:  
[Installers/Binaries](https://dotnet.microsoft.com/en-us/download/dotnet)  | ✅ | ✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Linux) | ✅| ✅ | ✅ 
[Container Images](https://hub.docker.com/_/microsoft-dotnet)<br>(Windows)  | ✅| ✅ | ✅ 
[Winget Packages](https://learn.microsoft.com/dotnet/core/install/windows#install-with-windows-package-manager-winget) | |  | 
**Linux Installers** (Microsoft distribution) | | | The list below refers to the Microsoft-provisioned feeds (packages.microsoft.com) and does not in any way represent direct availability in distros (eg RHEL, Fedora).
&nbsp;&nbsp;&nbsp;&nbsp; [Debian 12](https://learn.microsoft.com/dotnet/core/install/linux-debian) | ✅ | ✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [OpenSUSE 15](https://learn.microsoft.com/dotnet/core/install/linux-opensuse) ✅ | | ✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Rocky 9](https://learn.microsoft.com/dotnet/core/install/linux-rhel) | ✅  | ✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 20.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) ✅ | ✅ | ✅ 
&nbsp;&nbsp;&nbsp;&nbsp; [Ubuntu 22.04](https://learn.microsoft.com/dotnet/core/install/linux-ubuntu) | ✅| ✅ | ✅ 
## Issues
Please report any issues you find either by responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* ASP.NET Core: [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues)
* Entity Framework Core: [dotnet/efcore](https://github.com/dotnet/efcore/issues)
* .NET CLI/SDK [dotnet/sdk](https://github.com/dotnet/sdk/issues)
* .NET runtime [dotnet/runtime](https://github.com/dotnet/runtime/issues)
* Winforms: [dotnet/winforms](https://github.com/dotnet/winforms/issues)
* WPF: [dotnet/wpf](https://github.com/dotnet/wpf/issues)
* NuGet: [nuget/home](https://github.com/nuget/home/issues)
* Containers: [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker)
* Winget: [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by runesoerensen** [comment]
Hi,

The hashes appear to be wrong for some of today's SDK releases. For instance, [the hash for `dotnet-sdk-9.0.309-linux-arm64.tar.gz`](https://github.com/dotnet/core/blob/5c661ad3ebb329a78839ebcc7f78bc4f369421fa/release-notes/9.0/9.0.12/release.json#L135) is the [same as the last release in that feature band](https://github.com/dotnet/core/blob/5c661ad3ebb329a78839ebcc7f78bc4f369421fa/release-notes/9.0/9.0.11/release.json#L135) (`dotnet-sdk-9.0.308-linux-arm64.tar.gz`).

The actual SHA512 checksum for `https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.309/dotnet-sdk-9.0.309-linux-arm64.tar.gz` is `80f3ba0533a207ed39ccf0f43cfac4d6b96269b4ca539dabe0f379d5e31a812e103a56e4636b8475a191ea81285cd98231e10fb486de3c1c93dfd56bf4542e7c`.

I haven't tested all the checksums, but appears to affect several more, including:

* dotnet-sdk-10.0.102-linux-x64.tar.gz
* dotnet-sdk-8.0.417-linux-x64.tar.gz

The ARM64 versions of these releases also have invalid hashes listed in `release.json`

**Comment by rbhanda** [comment]
> Hi,
> 
> The hashes appear to be wrong for some of today's SDK releases. For instance, [the hash for `dotnet-sdk-9.0.309-linux-arm64.tar.gz`](https://github.com/dotnet/core/blob/5c661ad3ebb329a78839ebcc7f78bc4f369421fa/release-notes/9.0/9.0.12/release.json#L135) is the [same as the last release in that feature band](https://github.com/dotnet/core/blob/5c661ad3ebb329a78839ebcc7f78bc4f369421fa/release-notes/9.0/9.0.11/release.json#L135) (`dotnet-sdk-9.0.308-linux-arm64.tar.gz`).
> 
> The actual SHA512 checksum for `https://builds.dotnet.microsoft.com/dotnet/Sdk/9.0.309/dotnet-sdk-9.0.309-linux-arm64.tar.gz` is `80f3ba0533a207ed39ccf0f43cfac4d6b96269b4ca539dabe0f379d5e31a812e103a56e4636b8475a191ea81285cd98231e10fb486de3c1c93dfd56bf4542e7c`.
> 
> I haven't tested all the checksums, but appears to affect several more, including:
> 
> * dotnet-sdk-10.0.102-linux-x64.tar.gz
> * dotnet-sdk-8.0.417-linux-x64.tar.gz
> 
> The ARM64 versions of these releases also have invalid hashes listed in `release.json`

Thanks for catching this. https://github.com/dotnet/core/pull/10205/files to fix

**Comment by tbright92** [comment]
Hello!

For .NET 9.0.12, our build is failing when updating the `Microsoft.Extensions.ApiDescription.Server` NuGet package because it appears the `dotnet-getdocument.dll` and accompanying files aren't being published to the `tools` directory, so attempting to run `GenerateOpenApiDocuments` as part of the build is throwing an error.

I noticed this as part of our Renovate dependency update, so verified the build also fails running locally. If I copy that DLL from the 9.0.11/tools directory into 9.0.12/tools, the build succeeds.

Looking through the commit history, the only thing that stands out to me is [this PR](https://github.com/dotnet/aspnetcore/commit/a0b083ba0cb6ed9410d6ca432e1d1272dc5110ae#diff-265e032665460ea452aceaecfe5b20913ed92bb2b4a2be0dc57dd17338084fd3), but I don't see how that would've caused this to happen.

**Comment by reduckted** [comment]
I've experienced some weird behavior as well. I'm still trying to get a reproduction, but things worked fine on 10.0.101 SDK. Upgrading to 10.0.102 SDK results in `MissingMethodException` (or maybe it was an `EntryPointNotFoundException`, or maybe both in different scenarios) when using `dotnet run`. In fact, even staying on 10.0.101 SDK, but installing the 10.0.2 runtime (using `actions/setup-dotnet` which always installs the latest runtime) causes the same failure.

I know that's extremely vague, but like I said, I'm still trying to get a reproduction that I can share publicly. I'm just wondering if anyone else is experiencing things like this, or if something is somehow corrupted on my end?

**Comment by janpalas** [comment]
I am experiencing similar difficulties as well. Since Github Actions started using 10.0.102 SDK, I am not able to build my project (containing EF Core migrations) on Linux (`runs-on: ubuntu-latest` in yaml file) in Github Actions. I get this error:

`/usr/share/dotnet/sdk/10.0.102/Microsoft.Common.CurrentVersion.targets(3442,5): error MSB3552: Resource file "**/*.resx" cannot be found.` 

There are no *.resx files in my project and everything was working perfectly fine on 10.0.101 SDK

**Comment by wasabali** [comment]
experiencing the exact same thing as @jan-palas. Even tried to explicit set the version to 10.0.1 in the pipelines with `actions/setup-dotnet@4` and `actions/setup-dotnet@5` but it still downloads 10.0.2 and fails to find 10.0.1. 

<img width="1271" height="620" alt="Image" src="https://github.com/user-attachments/assets/771aa9de-bd83-4343-a25f-6fbbdd69e21c" />

**Comment by velartaginfocz** [comment]
As temporary solution, you can set appropriate steps to runs-on: windows-latest. Problem is only when it runs on linux

**Comment by michael-hawker** [comment]
The update to `9.0.309` [broke our CI](https://github.com/CommunityToolkit/Windows/actions/runs/21039291527/job/60496336614), all analyzers seemed to break:

>CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndMemberAccessDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\9.0.309\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CSharp.CodeStyle.dll : Exception has been thrown by the target of an invocation.. [D:\a\Labs-Windows\Labs-Windows\components\MarkdownTextBlock\src\CommunityToolkit.WinUI.Controls.MarkdownTextBlock.csproj::TargetFramework=net8.0-windows10.0.19041.0]

Rolling back to `9.0.308` resolves the issue.

I can see I can do a diff here for the SDK: https://github.com/dotnet/sdk/compare/v9.0.308...v9.0.309 - but it's hard to follow the circular chain of release notes to find these types of diffs or issue lists of things that got merged into the release that made this patch. Especially when things are split across repositories. Like the actual code for analyzers lives in the `roslyn` repo, but I'm not sure how that feeds into packaging...

Luckily at least seems like someone else has done this analysis already, issue here: https://github.com/dotnet/roslyn/issues/82010

**Comment by jimmylewis** [comment]
The 309 SDK is also breaking features in my VS2026 installation.  I'ts possibly the same root cause as [dotnet/roslyn#82010](https://github.com/dotnet/roslyn/issues/82010) but manifesting in VS features.

<img width="1884" height="188" alt="Image" src="https://github.com/user-attachments/assets/c669b1a3-7ff3-4157-a181-da64b5401b39" />

Repro steps:
1. Create a new console app targeting .NET 9
2. Add a global.json pinning the SDK to 9.0.309
3. Open the solution in VS and open a C# file

Does not reproduce for solutions using a different SDK.

**Comment by reduckted** [comment]
> I've experienced some weird behavior as well. I'm still trying to get a reproduction, but things worked fine on 10.0.101 SDK.

I was able to create a simple reproduction of the bug.
https://github.com/dotnet/runtime/issues/123254

**Comment by vrad-joshuamckelvey** [comment]
We are also seeing 309 breaking analyzers in automated CI builds using MSBuild + Bamboo on Windows Server 2016.

```
 CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.UseSystemHashCode.UseSystemHashCodeDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\9.0.309\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Exception has been thrown by the target of an invocation..
```

Happy to provide additional information if it is helpful.

**Comment by Cjewett** [comment]
Here to mimic that 9.0.309 is breaking all of our workflows.

```
An instance of analyzer Microsoft.CodeAnalysis.UseExplicitTupeName.UseExplicitTypeNameDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\9.0.309\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll: Exception has been thrown by the target of an invocation..
```

Is there a way to stop Microsoft / Visual Studio from auto upgrading the .NET SDK on Windows machines? Last we checked there wasn't but maybe asking that question here will provide us more insight. We did come across this in the past https://github.com/dotnet/core/issues/7457#issuecomment-1591871480 but even after installing the .NET SDK using CLI or scripts we received mixed results on Visual Studio auto upgrading their .NET SDK.

From our perspective our workflows have broken a few times in the last year due to auto .NET SDK updates and it does not feel like there are good solutions to prevent those fire drills from happening.

If you have no global.json then you're at the mercy of whatever the developer environment has locally which would also lead to broken development in auto update scenarios.

If you pin your global.json to a specific version it will work until Microsoft / Visual Studio takes it upon itself to automatically upgrade your .NET SDK version _and remove the previous version_. This breaks developer workflows until the global.json is upgraded in the repository and causes an unnecessary fire drill.

If your global.json uses latestFeature or latestPatch then issues like this most recent break occurs.

I understand that auto inheriting patch fixes is the suggested solution but in our experience when you auto inherit patch fixes across many different domains and technology stacks (.NET, Containers Images, NuGet packages, npm packages, etc.) things break very often. While everyone is supposed to follow best practices of what a patch version does in reality issues still occur despite best efforts. We don't need someone to auto upgrade us. We have the tooling in place to notify us of security flaws. We would much rather rely on those tools to facilitate security flaw resolution correctly and part of our validation pipeline.

**Comment by reduckted** [comment]
> If you pin your global.json to a specific version it will work until Microsoft / Visual Studio takes it upon itself to automatically upgrade your .NET SDK version _and remove the previous version_.

Yes, this is extremely frustrating. I disable roll forward because I want to know the exact version that is used in builds and deployments (and also to prevent things suddenly breaking because of bugs in new SDKs, which has happened in the past). Its understandable that Visual Studio would install the new SDK version, but having the previous version removed is so annoying.

**Comment by SweetLoverFT** [comment]
What does this mean?

Visual Studio support
Visual Studio 2026 (v18.2)
Included in
Visual Studio 18.2.0

**MUST** I install and use Visual Studio 2026 or VSCode 18.2.0? I prefer to use VS2022, currently the Visual Studio is too big!

**Comment by rbhanda** [comment]
closing in favor of https://github.com/dotnet/core/issues/10250
