### ISSUE TITLE
Possible bug with Reverse LINQ method when updating SDK to 9.0.2

### ISSUE THREAD

**Issue by danfma** [dotnet/core#9741]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/9.0/9.0.2/9.0.2.md

### Description

After updating to the SDK 9.0.2 from 9.0.0 I got a compilation error in a code that worked before. The Reverse LINQ operation was not being recognized anymore.

It's like if the IEnumerable Reverse extension method (which returns an IEnumerable<T>) is being replaced by the native `Array.Reverse` (which returns void). Causing the error below:

```
.../src/CarRacing/NeuralNetworks/NeuralNetworkTrainer.cs(90,30): error CS1579: foreach statement cannot operate on variables of type 'void' because 'void' does not contain a public instance or extension definition for 'GetEnumerator' [.../src/CarRacing/CarRacing.csproj]
```

![Image](https://github.com/user-attachments/assets/436cee4d-edd4-4f57-89e2-9df6154e0104)

**Comment by danfma** [comment]
Maybe it's the wrong place, so feel free to move/close this if that is the case.
